### 회원가입
POST http://localhost:3000/api/auth/sign-up
Content-Type: application/json

{
  "nickname": "문승호",
  "email": "test@example.com",
  "password": "!BNAas2333$",
  "passwordConfirm": "!BNAas2333$",
  "isAdmin": false
}
